#!/bin/bash

set -eu

LOCAL_BIN=~/.local/bin

DEFAULT_OWNER=
DEFAULT_NAME=
DEFAULT_EMAIL=
DEFAULT_LICENSE=
DEFAULT_GHC=

# Replace "template" strings (e.g. `{{DEFAULT_OWNER}}`) in
# `hs-init.hs` with user-provided values.
set_default() {
  local setting="$1"
  local value="$2"

  sed_match="{{$setting}}"
  sed_cmd="s/$sed_match/$value/"

  sed -i.orig "$sed_cmd" hs-init.hs
}

set_defaults() {
  [ -n "$DEFAULT_OWNER" ] && set_default DEFAULT_OWNER "$DEFAULT_OWNER"
  [ -n "$DEFAULT_NAME" ] && set_default DEFAULT_NAME "$DEFAULT_NAME"
  [ -n "$DEFAULT_EMAIL" ] && set_default DEFAULT_EMAIL "$DEFAULT_EMAIL"
  [ -n "$DEFAULT_LICENSE" ] && set_default DEFAULT_LICENSE "$DEFAULT_LICENSE"
  [ -n "$DEFAULT_GHC" ] && set_default DEFAULT_GHC "$DEFAULT_GHC"
}

# Cut down a bit on the noise of handling user input in a pipe.
read_default() {
  local prompt="$1"
  local dest="$2"

  IFS= read -p "$prompt" $dest <&2
}

# Prompt for and set default settings values in `hs-init.hs`. Any
# values not provided are simply left as their template strings.
populate_defaults() {
  read_default 'Default project owner: ' DEFAULT_OWNER
  read_default 'Default name: ' DEFAULT_NAME
  read_default 'Default email address: ' DEFAULT_EMAIL
  read_default 'Default license: ' DEFAULT_LICENSE
  read_default 'Default GHC version: ' DEFAULT_GHC

  set_defaults
}

wget https://raw.githubusercontent.com/vrom911/hs-init/master/hs-init.hs

populate_defaults

chmod +x hs-init.hs

[ -d "$LOCAL_BIN" ] || mkdir -p "$LOCAL_BIN"

mv hs-init.hs $LOCAL_BIN/hs-init
