#!/bin/bash

LOCAL_BIN=~/.local/bin

DEFAULT_OWNER=
DEFAULT_NAME=
DEFAULT_EMAIL=
DEFAULT_LICENSE=
DEFAULT_GHC=
DEFAULT_YEAR=

set_default() {
  local setting="$1"
  local value="$2"

  sed_match="{{$setting}}"
  sed_cmd="s/$sed_match/$value/"

  sed -i.orig "$sed_cmd" hs-init.hs
}

# Populate default settings
populate_defaults() {
  [ -n "$DEFAULT_OWNER" ] && set_default DEFAULT_OWNER "$DEFAULT_OWNER"
  [ -n "$DEFAULT_NAME" ] && set_default DEFAULT_NAME "$DEFAULT_NAME"
  [ -n "$DEFAULT_EMAIL" ] && set_default DEFAULT_EMAIL "$DEFAULT_EMAIL"
  [ -n "$DEFAULT_LICENSE" ] && set_default DEFAULT_LICENSE "$DEFAULT_LICENSE"
  [ -n "$DEFAULT_GHC" ] && set_default DEFAULT_GHC "$DEFAULT_GHC"
  [ -n "$DEFAULT_YEAR" ] && set_default DEFAULT_YEAR "$DEFAULT_YEAR"
}

wget https://raw.githubusercontent.com/vrom911/hs-init/master/hs-init.hs

populate_defaults

chmod +x hs-init.hs

[ -d "$LOCAL_BIN" ] || mkdir -p "$LOCAL_BIN"

mv hs-init.hs $LOCAL_BIN/hs-init
