#!/bin/bash

LOCAL_BIN=~/.local/bin

wget https://raw.githubusercontent.com/vrom911/hs-init/master/hs-init.hs
chmod +x hs-init.hs

[ -d "$LOCAL_BIN" ] || mkdir -p "$LOCAL_BIN"

mv hs-init.hs $LOCAL_BIN/hs-init
