resolver: nightly-2022-01-10

packages:
  - summoner-cli/
  - summoner-tui/

extra-deps:
  - colourista-0.1.0.1
  - generic-data-0.8.0.0
  - hashable-1.3.1.0
  - microaeson-0.1.0.0
  - optparse-applicative-0.16.0.0
  - relude-1.0.0.1
  - tomland-1.3.3.0
