resolver: lts-19.25

packages:
  - summoner-cli/
  - summoner-tui/

extra-deps:
  - colourista-0.1.0.1
  - megaparsec-9.0.1
  - microaeson-0.1.0.0
  - tomland-1.3.3.0
  - validation-selective-0.1.0.1
  - selective-0.4.2
