resolver: lts-19.31

packages:
  - summoner-cli/
  - summoner-tui/

extra-deps:
  - brick-1.3
  - bimap-0.5.0 # for brick
  - text-zipper-0.12 # for brick
  - colourista-0.1.0.2
  - tomland-1.3.3.2
  - validation-selective-0.1.0.1
  - vty-5.37
  - selective-0.4.2
